### ISSUE TITLE
Fail to install llm 0.5. failed to upgrade too. unistalled, tried to reinstall, same error 

### ISSUE THREAD

**Issue by dkmj** [simonw/homebrew-llm#2]
Last 15 lines from /Users/peternou/Library/Logs/Homebrew/llm/17.pip:

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /opt/homebrew/Cellar/llm/0.5/libexec/bin/python3.11 /opt/homebrew/Cellar/llm/0.5/libexec/lib/python3.11/site-packages/pip/__pip-runner__.py install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-_k7hf01_/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=1,<2' 'typing-extensions >=4.6.0,!=4.7.0'
  cwd: [inherit]
  Installing build dependencies: finished with status 'error'
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by dkmj** [comment]
python-typing-extensions on my system is updated at 4.7.1

**Comment by bcb44** [comment]
+1

**Comment by levitabris** [comment]
+1

**Comment by levitabris** [comment]
+1

**Comment by komatineni** [comment]
+1

**Comment by dictcp** [comment]
since `virtualenv_install_with_resources` does build python package locally, and the build process needs `rust`.
so installing. rust via `brew install rust` in advance should help

**Comment by dkmj** [comment]
Still fails for me. I did brew install rust, which did nothing to my env since rust was already installed. brew install simonw/llm/llm failed with same error as before, for me. 

I am pretty much a beginner when it comes to understanding and managung different py environments. In this case i try the 'simplest' brew install simonw/llm/llm as instructed...

**Comment by simonw** [comment]
Aha! Here's where it went wrong: https://github.com/simonw/homebrew-llm/commit/7fa54f63d8d6feebb4218f1faf130e55a75b8e23

That commit accidentally removed the `rust` bits.
